users_list:
    path:       /api/users
    controller: App\Controller\UserController::list
    methods:    GET|HEAD

users_edit:
    path:       /api/users/{id}
    controller: App\Controller\UserController::edit
    methods:    PUT

api_login_check:
    path: /api/login_check